"use client";

import { useEffect, useState } from "react";
type Profile={legalName?:string|null;accountHolder?:string|null;address?:string|null;postalCode?:string|null;city?:string|null;country?:string|null;iban?:string|null;bic?:string|null;bankName?:string|null;invoiceEmail?:string|null;paymentInstructions?:string|null;currency?:string|null};

export default function OwnerFacturationPage(){
 const [profile,setProfile]=useState<Profile>({country:"FR",currency:"EUR"}); const [message,setMessage]=useState("");
 useEffect(()=>{void fetch("/api/owner/billing-profile").then(r=>r.json()).then(d=>d.profile&&setProfile(d.profile));},[]);
 async function save(){setMessage("");const r=await fetch("/api/owner/billing-profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const d=await r.json();setMessage(r.ok?"Coordonnées de facturation enregistrées.":d.error||"Enregistrement impossible.");}
 const field=(key:keyof Profile,label:string,type="text")=><label className="block"><span className="mb-2 block text-[10px] uppercase tracking-[0.18em] text-white/45">{label}</span><input type={type} value={profile[key]??""} onChange={e=>setProfile(p=>({...p,[key]:e.target.value}))} className="w-full border border-white/10 bg-white/[0.03] px-4 py-3 text-sm outline-none focus:border-[#c7a15a]"/></label>;
 return <main className="min-h-screen bg-[#081625] px-6 py-14 text-white"><div className="mx-auto max-w-4xl"><p className="text-[10px] uppercase tracking-[0.28em] text-[#c7a15a]">OWNER · Facturation</p><h1 className="mt-3 font-serif text-4xl">Coordonnées de règlement</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50">Ces informations servent aux factures et aux instructions de virement des entreprises. Elles sont réservées à l'OWNER.</p><div className="mt-10 grid gap-5 border border-white/10 bg-white/[0.02] p-7 md:grid-cols-2">{field("legalName","Raison sociale")}{field("accountHolder","Titulaire du compte")}{field("bankName","Banque")}{field("iban","IBAN")}{field("bic","BIC / SWIFT")}{field("invoiceEmail","Email de facturation","email")}{field("address","Adresse")}{field("postalCode","Code postal")}{field("city","Ville")}{field("country","Pays (ISO)")}</div><label className="mt-5 block"><span className="mb-2 block text-[10px] uppercase tracking-[0.18em] text-white/45">Instructions de virement</span><textarea value={profile.paymentInstructions??""} onChange={e=>setProfile(p=>({...p,paymentInstructions:e.target.value}))} rows={4} className="w-full border border-white/10 bg-white/[0.03] px-4 py-3 text-sm outline-none focus:border-[#c7a15a]"/></label><button onClick={()=>void save()} className="mt-6 border border-[#c7a15a] px-6 py-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#c7a15a]">Enregistrer</button>{message&&<p className="mt-4 text-sm text-white/55">{message}</p>}</div></main>;
}