import { createPartner, ActorInfo } from "./partner-service";
import { isRecruitmentPlatform, PartnerStatusCode } from "./taxonomy";

export interface DiscoveredPartner {
  officialName: string;
  usualName?: string;
  category: string;
  subCategory?: string;
  partnerType?: string;
  country?: string;
  region?: string;
  city?: string;
  website?: string;
  institutionalAddress?: string;
  publicContactEmail?: string;
  publicContactPhone?: string;
  languages?: string[];
  sectors?: string[];
  professions?: string[];
  targetAudience?: string[];
  collaborationTypes?: string[];
  potentialNeed?: string;
  source: string;
  sourceUrl?: string;
  discoveredAt: string;
  notes?: string;
}

const CURATED_INSTITUTIONAL_PARTNERS: DiscoveredPartner[] = [
  {
    officialName: "CCI France International",
    usualName: "CCIFI",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_INTERNATIONALE",
    partnerType: "Réseau Consulaire",
    country: "France",
    city: "Paris",
    website: "https://www.ccifrance-international.org",
    publicContactEmail: "contact@ccifrance-international.org",
    languages: ["Français", "Anglais"],
    sectors: ["Commerce International", "Industrie", "Services"],
    targetAudience: ["Entreprises", "Cadres à l'international", "Expatriés"],
    collaborationTypes: ["Relais économique", "Mise en relation", "Événements"],
    source: "ANNUAIRE_OFFICIEL_CCIFI",
    sourceUrl: "https://www.ccifrance-international.org",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau mondial de 119 chambres de commerce françaises à l'étranger dans 94 pays.",
  },
  {
    officialName: "Campus France",
    usualName: "Campus France",
    category: "UNIVERSITES_ECOLES",
    subCategory: "SERVICE_CARRIERE",
    partnerType: "Établissement public",
    country: "France",
    city: "Paris",
    website: "https://www.campusfrance.org",
    publicContactEmail: "info@campusfrance.org",
    languages: ["Français", "Anglais", "Espagnol"],
    sectors: ["Enseignement Supérieur", "Recherche", "Mobilité"],
    targetAudience: ["Étudiants internationaux", "Jeunes diplômés", "Chercheurs"],
    collaborationTypes: ["Mobilité internationale", "Attractivité des talents"],
    source: "INSTITUTIONNEL_ETAT",
    sourceUrl: "https://www.campusfrance.org",
    discoveredAt: new Date().toISOString(),
    notes: "Agence française pour la promotion de l'enseignement supérieur, l'accueil et la mobilité internationale.",
  },
  {
    officialName: "Union des Français de l'Étranger",
    usualName: "UFE",
    category: "RESEAUX_EXPATRIES",
    subCategory: "ASSOCIATION_EXPATRIES",
    partnerType: "Association d'utilité publique",
    country: "France",
    city: "Paris",
    website: "https://www.ufe.org",
    publicContactEmail: "contact@ufe.org",
    languages: ["Français"],
    sectors: ["Accompagnement", "Réseau", "Entraide"],
    targetAudience: ["Expatriés français", "Familles d'expatriés", "Cadres internationaux"],
    collaborationTypes: ["Accueil des talents", "Réseau professionnel de diaspora"],
    source: "RESEAU_EXPAT_MONDE",
    sourceUrl: "https://www.ufe.org",
    discoveredAt: new Date().toISOString(),
    notes: "Association reconnue d'utilité publique regroupant les Français, francophones et francophiles à l'étranger.",
  },
  {
    officialName: "Français du Monde - ADFE",
    usualName: "FDM-ADFE",
    category: "RESEAUX_EXPATRIES",
    subCategory: "ASSOCIATION_EXPATRIES",
    partnerType: "Association Loi 1901",
    country: "France",
    city: "Paris",
    website: "https://www.francais-du-monde.org",
    publicContactEmail: "adfe@francais-du-monde.org",
    languages: ["Français"],
    sectors: ["Solidarité", "Insertion", "Citoyenneté"],
    targetAudience: ["Expatriés", "Travailleurs à l'international"],
    collaborationTypes: ["Relais d'information", "Accompagnement mobilité"],
    source: "RESEAU_EXPAT_MONDE",
    sourceUrl: "https://www.francais-du-monde.org",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau associatif représentatif des citoyens français établis hors de France.",
  },
  {
    officialName: "Conférence des Grandes Écoles",
    usualName: "CGE",
    category: "UNIVERSITES_ECOLES",
    subCategory: "ETABLISSEMENT_SUPERIEUR",
    partnerType: "Association d'écoles",
    country: "France",
    city: "Paris",
    website: "https://www.cge.asso.fr",
    publicContactEmail: "contact@cge.asso.fr",
    languages: ["Français", "Anglais"],
    sectors: ["Ingénierie", "Management", "Grandes Écoles"],
    targetAudience: ["Ingénieurs", "Cadres dirigeants", "Alumni grandes écoles"],
    collaborationTypes: ["Convention d'échange", "Placement diplômés"],
    source: "FEDERATION_ENSEIGNEMENT",
    sourceUrl: "https://www.cge.asso.fr",
    discoveredAt: new Date().toISOString(),
    notes: "Association regroupant plus de 230 grandes écoles d'ingénieurs, de management et de spécialités.",
  },
  {
    officialName: "Réseau France Alumni",
    usualName: "France Alumni",
    category: "UNIVERSITES_ECOLES",
    subCategory: "ALUMNI",
    partnerType: "Plateforme institutionnelle",
    country: "France",
    city: "Paris",
    website: "https://www.francealumni.fr",
    publicContactEmail: "alumni@campusfrance.org",
    languages: ["Français", "Anglais"],
    sectors: ["Tous secteurs", "International"],
    targetAudience: ["Alumni internationaux de l'enseignement supérieur français"],
    collaborationTypes: ["Diffusion réseau", "Événements networking"],
    source: "RESEAU_INSTITUTIONNEL_ALUMNI",
    sourceUrl: "https://www.francealumni.fr",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau officiel des anciens étudiants internationaux ayant effectué leurs études en France.",
  },
  // --- EUROPE ---
  {
    officialName: "Chambre Franco-Allemande de Commerce et d'Industrie",
    usualName: "AHK Frankreich",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre Bilatérale",
    country: "Allemagne",
    city: "Francfort / Paris",
    website: "https://www.franzaus.de",
    publicContactEmail: "info@franzaus.de",
    languages: ["Allemand", "Français"],
    sectors: ["Commerce", "Industrie", "Technologies"],
    targetAudience: ["Entreprises bilatérales", "Cadres bilingues", "Expatriés"],
    collaborationTypes: ["Développement économique", "Réseau d'affaires"],
    source: "ANNUAIRE_OFFICIEL_AHK",
    sourceUrl: "https://www.franzaus.de",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau officiel de commerce franco-allemand favorisant la mobilité des cadres et des talents.",
  },
  {
    officialName: "Chambre de Commerce Franco-Belge",
    usualName: "CCFB",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Belgique",
    city: "Bruxelles",
    website: "https://www.ccfb.be",
    publicContactEmail: "contact@ccfb.be",
    languages: ["Français", "Néerlandais"],
    sectors: ["Services", "Finance", "Logistique"],
    targetAudience: ["Entreprises transfrontalières", "Cadres franco-belges"],
    collaborationTypes: ["Partenariat économique", "Événements"],
    source: "ANNUAIRE_CCIFI",
    sourceUrl: "https://www.ccfb.be",
    discoveredAt: new Date().toISOString(),
    notes: "Accompagnement des entreprises et cadres dans les échanges transfrontaliers franco-belges.",
  },
  {
    officialName: "Chambre de Commerce Française au Luxembourg",
    usualName: "CCFL",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Luxembourg",
    city: "Luxembourg",
    website: "https://www.ccfl.lu",
    publicContactEmail: "info@ccfl.lu",
    languages: ["Français", "Anglais", "Allemand"],
    sectors: ["Finance", "Fintech", "Conseil"],
    targetAudience: ["Cadres financiers", "Frontaliers", "Expatriés"],
    collaborationTypes: ["Mise en relation", "Networking"],
    source: "ANNUAIRE_CCIFI",
    sourceUrl: "https://www.ccfl.lu",
    discoveredAt: new Date().toISOString(),
    notes: "Plateforme d'échange pour les acteurs économiques et talents du Grand-Duché et de France.",
  },
  {
    officialName: "Chambre de Commerce Franco-Suisse",
    usualName: "CCIFS",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Suisse",
    city: "Genève / Zurich",
    website: "https://www.ccifs.ch",
    publicContactEmail: "contact@ccifs.ch",
    languages: ["Français", "Allemand", "Anglais"],
    sectors: ["Banque", "Horlogerie", "Santé"],
    targetAudience: ["Cadres dirigeants", "Frontaliers", "Expatriés qualifiés"],
    collaborationTypes: ["Relais économique", "Mise en relation"],
    source: "ANNUAIRE_CCIFI",
    sourceUrl: "https://www.ccifs.ch",
    discoveredAt: new Date().toISOString(),
    notes: "Soutien aux échanges bilatéraux et recrutement de talents hautement qualifiés entre la France et la Suisse.",
  },
  {
    officialName: "Chambre de Commerce Franco-Espagnole",
    usualName: "La Chambre / CCIFE",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Espagne",
    city: "Madrid / Barcelone",
    website: "https://www.lafrenchtechmadrid.com",
    publicContactEmail: "contact@lachambre.es",
    languages: ["Espagnol", "Français"],
    sectors: ["Tech", "Tourisme", "Énergie"],
    targetAudience: ["Cadres francophones en Espagne", "Expatriés"],
    collaborationTypes: ["Réseau d'affaires", "Networking"],
    source: "ANNUAIRE_CCIFI",
    sourceUrl: "https://www.lachambre.es",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau incontournable d'entreprises et de professionnels franco-espagnols.",
  },
  {
    officialName: "French Chamber of Great Britain",
    usualName: "CCFGB",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Royaume-Uni",
    city: "Londres",
    website: "https://www.frenchchamber.co.uk",
    publicContactEmail: "info@frenchchamber.co.uk",
    languages: ["Anglais", "Français"],
    sectors: ["Finance", "Tech", "Luxe"],
    targetAudience: ["Cadres à Londres", "Expatriés français au UK"],
    collaborationTypes: ["Club d'affaires", "Réseau alumni"],
    source: "ANNUAIRE_CCIFI",
    sourceUrl: "https://www.frenchchamber.co.uk",
    discoveredAt: new Date().toISOString(),
    notes: "Plus grande chambre de commerce bilatérale au Royaume-Uni facilitant l'intégration des talents.",
  },
  // --- GOLFE ---
  {
    officialName: "French Business Council Dubai & Northern Emirates",
    usualName: "FBC Dubaï / CCI France UAE",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Émirats arabes unis",
    city: "Dubaï / Abou Dabi",
    website: "https://www.ccifranceuae.com",
    publicContactEmail: "contact@ccifranceuae.com",
    languages: ["Anglais", "Français", "Arabe"],
    sectors: ["Finance", "Luxe", "Énergie", "Technologies"],
    targetAudience: ["Cadres internationaux", "Expatriés francophones", "Chefs d'entreprise"],
    collaborationTypes: ["Mise en relation", "Réseau des expatriés"],
    source: "ANNUAIRE_CCIFI_GOLFE",
    sourceUrl: "https://www.ccifranceuae.com",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau majeur d'affaires français aux Émirats Arabes Unis favorisant la mobilité des exécutifs.",
  },
  {
    officialName: "French Business Group Saudi Arabia",
    usualName: "CAFS Saudi Arabia",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Conseil d'affaires",
    country: "Arabie saoudite",
    city: "Riyad",
    website: "https://www.cafs.org.sa",
    publicContactEmail: "info@cafs.org.sa",
    languages: ["Anglais", "Arabe", "Français"],
    sectors: ["Infrastructures", "Vision 2030", "Énergie", "Conseil"],
    targetAudience: ["Experts internationaux", "Ingénieurs", "Cadres d'exception"],
    collaborationTypes: ["Partenariat stratégique", "Recrutement d'experts"],
    source: "ANNUAIRE_GOLFE",
    sourceUrl: "https://www.cafs.org.sa",
    discoveredAt: new Date().toISOString(),
    notes: "Conseil d'affaires franco-saoudien accompagnant les grands projets Vision 2030.",
  },
  {
    officialName: "Maison de la France au Qatar",
    usualName: "Maison de la France Qatar / QFC",
    category: "RESEAUX_EXPATRIES",
    subCategory: "ASSOCIATION_EXPATRIES",
    partnerType: "Réseau d'affaires",
    country: "Qatar",
    city: "Doha",
    website: "https://www.qatar-france.org",
    publicContactEmail: "contact@qatar-france.org",
    languages: ["Anglais", "Français", "Arabe"],
    sectors: ["Gas & Oil", "Sport Management", "Finance"],
    targetAudience: ["Expatriés qualifiés", "Cadres dirigeants"],
    collaborationTypes: ["Réseau institutionnel"],
    source: "RESEAU_EXPAT_GOLFE",
    sourceUrl: "https://www.qatar-france.org",
    discoveredAt: new Date().toISOString(),
    notes: "Association favorisant les synergies professionnelles entre la France et le Qatar.",
  },
  // --- AFRIQUE ---
  {
    officialName: "Chambre Française de Commerce et d'Industrie du Maroc",
    usualName: "CFCIM",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Maroc",
    city: "Casablanca / Rabat",
    website: "https://www.cfcim.org",
    publicContactEmail: "cfcim@cfcim.org",
    languages: ["Français", "Arabe"],
    sectors: ["Automobile", "Aéronautique", "Offshoring", "Finance"],
    targetAudience: ["Dirigeants", "Cadres supérieurs", "Repat et expatriés"],
    collaborationTypes: ["Mise en relation", "Emploi & Formation"],
    source: "ANNUAIRE_CFCIM",
    sourceUrl: "https://www.cfcim.org",
    discoveredAt: new Date().toISOString(),
    notes: "Plus importante chambre bilatérale du réseau CCIFI dans le monde.",
  },
  {
    officialName: "Chambre Tuniso-Française de Commerce et d'Industrie",
    usualName: "CTFCI",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Tunisie",
    city: "Tunis",
    website: "https://www.ctfci.org",
    publicContactEmail: "contact@ctfci.org",
    languages: ["Français", "Arabe"],
    sectors: ["IT & Software", "Textile", "Industrie", "Services"],
    targetAudience: ["Ingénieurs IT", "Cadres tunisiens et français"],
    collaborationTypes: ["Partenariat stratégique"],
    source: "ANNUAIRE_CCIFI",
    sourceUrl: "https://www.ctfci.org",
    discoveredAt: new Date().toISOString(),
    notes: "Acteur clé dans le développement du hub technologique et de compétences franco-tunisien.",
  },
  {
    officialName: "Chambre de Commerce et d'Industrie Franco-Sénégalaise",
    usualName: "CCI France Sénégal",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Sénégal",
    city: "Dakar",
    website: "https://www.ccifs.sn",
    publicContactEmail: "info@ccifs.sn",
    languages: ["Français"],
    sectors: ["Mines & Énergie", "Banque", "Telecoms", "Logistique"],
    targetAudience: ["Cadres dirigeants", "Cadres diplômés"],
    collaborationTypes: ["Relais Afrique de l'Ouest"],
    source: "ANNUAIRE_CCIFI_AFRIQUE",
    sourceUrl: "https://www.ccifs.sn",
    discoveredAt: new Date().toISOString(),
    notes: "Plateforme économique majeure en Afrique de l'Ouest pour les talents et entreprises francophones.",
  },
  {
    officialName: "Chambre de Commerce et d'Industrie Française en Côte d'Ivoire",
    usualName: "CCIFCI",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Côte d'Ivoire",
    city: "Abidjan",
    website: "https://www.ccifci.org",
    publicContactEmail: "info@ccifci.org",
    languages: ["Français"],
    sectors: ["Agro-industrie", "Infrastructures", "Services financiers"],
    targetAudience: ["Repats", "Expatriés", "Cadres ouest-africains"],
    collaborationTypes: ["Accompagnement mobilité"],
    source: "ANNUAIRE_CCIFI_AFRIQUE",
    sourceUrl: "https://www.ccifci.org",
    discoveredAt: new Date().toISOString(),
    notes: "Chambre bilatérale historique basée à Abidjan pour le développement régional.",
  },
  // --- ASIE ---
  {
    officialName: "French Chamber of Commerce in Singapore",
    usualName: "FCCS",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Singapour",
    city: "Singapour",
    website: "https://www.fccsingapore.com",
    publicContactEmail: "info@fccsingapore.com",
    languages: ["Anglais", "Français"],
    sectors: ["Fintech", "Logistique Maritime", "Smart City"],
    targetAudience: ["Exécutifs Asie-Pacifique", "Cadres internationaux"],
    collaborationTypes: ["Hub Asie-Pacifique"],
    source: "ANNUAIRE_CCIFI_ASIE",
    sourceUrl: "https://www.fccsingapore.com",
    discoveredAt: new Date().toISOString(),
    notes: "Hub d'affaires stratégique facilitant le recrutement international dans la zone ASEAN.",
  },
  {
    officialName: "Indo-French Chamber of Commerce and Industry",
    usualName: "IFCCI",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Inde",
    city: "Mumbai / New Delhi / Bangalore",
    website: "https://www.ifcci.org.in",
    publicContactEmail: "contact@ifcci.org.in",
    languages: ["Anglais"],
    sectors: ["IT", "Aéronautique", "Santé", "R&D"],
    targetAudience: ["Ingénieurs indiens", "Cadres bilingues"],
    collaborationTypes: ["Recrutement d'experts IT"],
    source: "ANNUAIRE_IFCCI",
    sourceUrl: "https://www.ifcci.org.in",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau reliant l'écosystème d'innovation indien et les groupes internationaux.",
  },
  // --- AMÉRIQUE DU NORD ---
  {
    officialName: "French-American Chamber of Commerce",
    usualName: "FACC USA",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "États-Unis",
    city: "New York / San Francisco",
    website: "https://www.faccnyc.org",
    publicContactEmail: "info@faccnyc.org",
    languages: ["Anglais", "Français"],
    sectors: ["Finance", "Biotech", "Tech", "Luxe"],
    targetAudience: ["Cadres aux USA", "Expatriés", "Exécutifs"],
    collaborationTypes: ["Réseau bilatéral", "Échanges de compétences"],
    source: "ANNUAIRE_FACC",
    sourceUrl: "https://www.faccnyc.org",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau national FACC aux États-Unis soutenant la mobilité professionnelle transatlantique.",
  },
  {
    officialName: "Chambre de Commerce Française au Canada",
    usualName: "CCFCA",
    category: "CHAMBRES_COMMERCE",
    subCategory: "CCI_BILATERALE",
    partnerType: "Chambre de Commerce",
    country: "Canada",
    city: "Montréal / Toronto",
    website: "https://www.fccanada.com",
    publicContactEmail: "contact@fccanada.com",
    languages: ["Français", "Anglais"],
    sectors: ["IA & Software", "Jeux Vidéo", "Énergie", "Aéronautique"],
    targetAudience: ["Talents francophones", "Immigrants qualifiés", "Cadres"],
    collaborationTypes: ["Mobilité Canada-France"],
    source: "ANNUAIRE_CCFCA",
    sourceUrl: "https://www.fccanada.com",
    discoveredAt: new Date().toISOString(),
    notes: "Réseau privilégié pour l'accompagnement des talents au Québec et dans tout le Canada.",
  },
];

export async function discoverInstitutionalPartners(query?: {
  category?: string;
  country?: string;
  q?: string;
}): Promise<DiscoveredPartner[]> {
  let results = [...CURATED_INSTITUTIONAL_PARTNERS];

  results = results.filter((p) => !isRecruitmentPlatform(p.officialName, p.notes, p.website));

  if (query?.category) {
    results = results.filter((p) => p.category === query.category);
  }

  if (query?.country) {
    const term = query.country.toLowerCase();
    results = results.filter((p) => p.country?.toLowerCase().includes(term));
  }

  if (query?.q) {
    const term = query.q.toLowerCase();
    results = results.filter(
      (p) =>
        p.officialName.toLowerCase().includes(term) ||
        p.usualName?.toLowerCase().includes(term) ||
        p.notes?.toLowerCase().includes(term) ||
        p.city?.toLowerCase().includes(term) ||
        p.country?.toLowerCase().includes(term)
    );
  }

  return results;
}

export async function importDiscoveredPartner(
  partner: DiscoveredPartner,
  actor: ActorInfo,
  initialStatus: PartnerStatusCode = "IDENTIFIED"
) {
  if (isRecruitmentPlatform(partner.officialName, partner.notes, partner.website)) {
    throw new Error("EXCLUSION_RECRUITMENT_PLATFORM: Les plateformes de recrutement sont strictement exclues.");
  }

  return createPartner(
    {
      officialName: partner.officialName,
      usualName: partner.usualName,
      category: partner.category,
      subCategory: partner.subCategory,
      partnerType: partner.partnerType,
      status: initialStatus,
      country: partner.country,
      region: partner.region,
      city: partner.city,
      website: partner.website,
      institutionalAddress: partner.institutionalAddress,
      publicContactEmail: partner.publicContactEmail,
      publicContactPhone: partner.publicContactPhone,
      languages: partner.languages,
      sectors: partner.sectors,
      professions: partner.professions,
      targetAudience: partner.targetAudience,
      collaborationTypes: partner.collaborationTypes,
      potentialNeed: partner.potentialNeed,
      notes: partner.notes,
      source: partner.source,
      sourceUrl: partner.sourceUrl,
    },
    actor
  );
}
