export type TaxonomyPositioning = Record<string, string>;

export const RP_POSITIONING: TaxonomyPositioning = {
  fr: "Cadres supérieurs & profils rares",
  en: "Senior leaders & rare profiles",
  es: "Altos perfiles directivos y perfiles raros",
  de: "Führungskräfte & seltene Spezialisten",
  it: "Quadri e profili rari",
  ar: "الكفاءات القيادية والتنفيذية والمتخصصون ذوو الندرة",
  nl: "Senior executives & zeldzame profielen",
};

export type TaxonomyNode = {
  code: string;
  name: Record<string, string>;
  positioning: TaxonomyPositioning;
  subcategories: Array<{ code: string; name: Record<string, string>; positioning: TaxonomyPositioning }>;
};

export const RP_TAXONOMY: TaxonomyNode[] = [
  { code: "INDUSTRIE", name: { fr: "Industrie", en: "Industry", es: "Industria", de: "Industrie", it: "Industria", nl: "Industrie", ar: "الصناعة" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "PRODUCTION", name: { fr: "Production", en: "Production", es: "Producción", de: "Produktion", it: "Produzione", nl: "Productie", ar: "الإنتاج" },
      positioning: RP_POSITIONING },
    { code: "MAINTENANCE", name: { fr: "Maintenance", en: "Maintenance", es: "Mantenimiento", de: "Instandhaltung", it: "Manutenzione", nl: "Onderhoud", ar: "الصيانة" },
      positioning: RP_POSITIONING },
    { code: "QUALITE", name: { fr: "Qualité / QHSE", en: "Quality / HSE", es: "Calidad / HSE", de: "Qualität / HSE", it: "Qualità / HSE", nl: "Kwaliteit / HSE", ar: "الجودة / السلامة" },
      positioning: RP_POSITIONING },
    { code: "METHODES_INDUSTRIELLES", name: { fr: "Méthodes / Industrialisation", en: "Industrial Engineering", es: "Métodos / Industrialización", de: "Industrial Engineering", it: "Metodi / Industrializzazione", nl: "Methoden / Industrialisatie", ar: "الهندسة الصناعية" },
      positioning: RP_POSITIONING },
    { code: "SUPPLY_INDUSTRIELLE", name: { fr: "Supply chain industrielle", en: "Industrial Supply Chain", es: "Cadena de suministro industrial", de: "Industrielle Lieferkette", it: "Supply chain industriale", nl: "Industriële Supply Chain", ar: "سلسلة التوريد الصناعية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "LOGISTIQUE", name: { fr: "Logistique & Supply Chain", en: "Logistics & Supply Chain", es: "Logística y Supply Chain", de: "Logistik & Supply Chain", it: "Logistica e Supply Chain", nl: "Logistiek & Supply Chain", ar: "اللوجستيات وسلسلة الإمداد" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "LOGISTIQUE_TRANSPORT", name: { fr: "Logistique / Transport", en: "Logistics / Transport", es: "Logística / Transporte", de: "Logistik / Transport", it: "Logistica / Trasporti", nl: "Logistiek / Transport", ar: "اللوجستيات / النقل" },
      positioning: RP_POSITIONING },
    { code: "ACHATS", name: { fr: "Achats", en: "Procurement", es: "Compras", de: "Einkauf", it: "Acquisti", nl: "Inkoop", ar: "المشتريات" },
      positioning: RP_POSITIONING },
    { code: "SUPPLY_CHAIN", name: { fr: "Supply Chain", en: "Supply Chain", es: "Supply Chain", de: "Supply Chain", it: "Supply Chain", nl: "Supply Chain", ar: "سلسلة الإمداد" },
      positioning: RP_POSITIONING },
    { code: "PLANIFICATION", name: { fr: "Planification / Ordonnancement", en: "Planning / Scheduling", es: "Planificación / Programación", de: "Planung / Disposition", it: "Pianificazione", nl: "Planning / Werkvoorbereiding", ar: "التخطيط والجدولة" },
      positioning: RP_POSITIONING },
    { code: "WAREHOUSING", name: { fr: "Entrepôt / Warehouse", en: "Warehousing", es: "Almacén", de: "Lager", it: "Magazzino", nl: "Magazijn / Warehousing", ar: "المستودعات" },
      positioning: RP_POSITIONING },
  ]},
  { code: "COMMERCE", name: { fr: "Commerce & Business", en: "Sales & Business", es: "Comercio y Negocio", de: "Vertrieb & Business", it: "Vendite e Business", nl: "Verkoop & Business", ar: "التجارة والأعمال" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "VENTE_B2B", name: { fr: "Vente B2B", en: "B2B Sales", es: "Ventas B2B", de: "B2B-Vertrieb", it: "Vendite B2B", nl: "B2B-verkoop", ar: "مبيعات B2B" },
      positioning: RP_POSITIONING },
    { code: "GRANDS_COMPTES", name: { fr: "Grands comptes / Key Account", en: "Key Account Management", es: "Grandes cuentas", de: "Key Account Management", it: "Key Account", nl: "Key Account Management", ar: "إدارة الحسابات الرئيسية" },
      positioning: RP_POSITIONING },
    { code: "BUSINESS_DEV", name: { fr: "Business Development", en: "Business Development", es: "Desarrollo de negocio", de: "Business Development", it: "Business Development", nl: "Business Development", ar: "تطوير الأعمال" },
      positioning: RP_POSITIONING },
    { code: "DIRECTION_COMMERCIALE", name: { fr: "Direction commerciale", en: "Sales Leadership", es: "Dirección comercial", de: "Vertriebsleitung", it: "Direzione commerciale", nl: "Commerciële directie", ar: "الإدارة التجارية" },
      positioning: RP_POSITIONING },
    { code: "VENTE_RETAIL", name: { fr: "Retail / Point de vente", en: "Retail", es: "Retail", de: "Einzelhandel", it: "Retail", nl: "Retail / Verkooppunt", ar: "تجارة التجزئة" },
      positioning: RP_POSITIONING },
  ]},
  { code: "SERVICES", name: { fr: "Services", en: "Services", es: "Servicios", de: "Dienstleistungen", it: "Servizi", nl: "Diensten", ar: "الخدمات" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "CONSEIL", name: { fr: "Conseil", en: "Consulting", es: "Consultoría", de: "Beratung", it: "Consulenza", nl: "Consultancy", ar: "الاستشارات" },
      positioning: RP_POSITIONING },
    { code: "RELATION_CLIENT", name: { fr: "Relation client / Customer Success", en: "Customer Success", es: "Relación cliente", de: "Kundenbetreuung", it: "Customer Success", nl: "Klantrelaties / Customer Success", ar: "نجاح العملاء" },
      positioning: RP_POSITIONING },
    { code: "OPERATIONS", name: { fr: "Opérations", en: "Operations", es: "Operaciones", de: "Operations", it: "Operations", nl: "Operations", ar: "العمليات" },
      positioning: RP_POSITIONING },
    { code: "SERVICES_GENERAUX", name: { fr: "Services généraux", en: "General Services", es: "Servicios generales", de: "Allgemeine Dienste", it: "Servizi generali", nl: "Algemene diensten", ar: "الخدمات العامة" },
      positioning: RP_POSITIONING },
  ]},
  { code: "IT", name: { fr: "Informatique & Tech", en: "IT & Technology", es: "Tecnología e IT", de: "IT & Technologie", it: "IT e Tecnologia", nl: "IT & Technologie", ar: "تقنية المعلومات والتكنولوجيا" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "DEV_LOGICIEL", name: { fr: "Développement logiciel", en: "Software Development", es: "Desarrollo de software", de: "Softwareentwicklung", it: "Sviluppo software", nl: "Softwareontwikkeling", ar: "تطوير البرمجيات" },
      positioning: RP_POSITIONING },
    { code: "DATA_IA", name: { fr: "Data / IA / Machine Learning", en: "Data / AI / Machine Learning", es: "Datos / IA / Machine Learning", de: "Data / KI / Machine Learning", it: "Data / IA / Machine Learning", nl: "Data / AI / Machine Learning", ar: "البيانات والذكاء الاصطناعي" },
      positioning: RP_POSITIONING },
    { code: "CYBERSECURITE", name: { fr: "Cybersécurité", en: "Cybersecurity", es: "Ciberseguridad", de: "Cybersicherheit", it: "Cybersecurity", nl: "Cybersecurity", ar: "الأمن السيبراني" },
      positioning: RP_POSITIONING },
    { code: "CLOUD_DEVOPS", name: { fr: "Cloud / DevOps / SRE", en: "Cloud / DevOps / SRE", es: "Cloud / DevOps / SRE", de: "Cloud / DevOps / SRE", it: "Cloud / DevOps / SRE", nl: "Cloud / DevOps / SRE", ar: "السحابة و DevOps" },
      positioning: RP_POSITIONING },
    { code: "ROBOTIQUE_IOT", name: { fr: "Robotique / IoT", en: "Robotics / IoT", es: "Robótica / IoT", de: "Robotik / IoT", it: "Robotica / IoT", nl: "Robotica / IoT", ar: "الروبوتات وإنترنت الأشياء" },
      positioning: RP_POSITIONING },
    { code: "PRODUIT_TECH", name: { fr: "Product Management / UX-UI", en: "Product Management / UX-UI", es: "Product Management / UX-UI", de: "Product Management / UX-UI", it: "Product Management / UX-UI", nl: "Productmanagement / UX-UI", ar: "إدارة المنتجات وتجربة المستخدم" },
      positioning: RP_POSITIONING },
  ]},
  { code: "BTP", name: { fr: "BTP & Construction", en: "Construction", es: "Construcción", de: "Bau", it: "Edilizia", nl: "Bouw & Constructie", ar: "البناء والتشييد" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "CONDUITE_TRAVAUX", name: { fr: "Conduite de travaux", en: "Construction Management", es: "Dirección de obra", de: "Bauleitung", it: "Direzione lavori", nl: "Bouwmanagement", ar: "إدارة أعمال البناء" },
      positioning: RP_POSITIONING },
    { code: "GENIE_CIVIL", name: { fr: "Génie civil", en: "Civil Engineering", es: "Ingeniería civil", de: "Bauingenieurwesen", it: "Ingegneria civile", nl: "Civiele techniek", ar: "الهندسة المدنية" },
      positioning: RP_POSITIONING },
    { code: "ELECTRICITE_BATIMENT", name: { fr: "Électricité bâtiment", en: "Building Electrical", es: "Electricidad de edificios", de: "Gebäudeelektrik", it: "Elettricità edilizia", nl: "Gebouwelektriciteit", ar: "كهرباء المباني" },
      positioning: RP_POSITIONING },
    { code: "CVC_PLOMBERIE", name: { fr: "CVC / Plomberie", en: "HVAC / Plumbing", es: "Climatización / Fontanería", de: "SHK / Gebäudetechnik", it: "HVAC / Idraulica", nl: "HVAC / Loodgieterij", ar: "التكييف والسباكة" },
      positioning: RP_POSITIONING },
    { code: "INGENIERIE_BATIMENT", name: { fr: "Ingénierie bâtiment", en: "Building Engineering", es: "Ingeniería de edificación", de: "Gebäudetechnik", it: "Ingegneria edilizia", nl: "Bouwtechniek", ar: "هندسة المباني" },
      positioning: RP_POSITIONING },
  ]},
  { code: "FINANCE", name: { fr: "Finance", en: "Finance", es: "Finanzas", de: "Finanzen", it: "Finanza", nl: "Financiën", ar: "المالية" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "COMPTABILITE", name: { fr: "Comptabilité", en: "Accounting", es: "Contabilidad", de: "Buchhaltung", it: "Contabilità", nl: "Boekhouding", ar: "المحاسبة" },
      positioning: RP_POSITIONING },
    { code: "CONTROLE_DE_GESTION", name: { fr: "Contrôle de gestion", en: "Financial Controlling", es: "Control de gestión", de: "Controlling", it: "Controllo di gestione", nl: "Management control", ar: "الرقابة الإدارية والمالية" },
      positioning: RP_POSITIONING },
    { code: "AUDIT", name: { fr: "Audit", en: "Audit", es: "Auditoría", de: "Audit", it: "Audit", nl: "Audit", ar: "التدقيق" },
      positioning: RP_POSITIONING },
    { code: "TRESORERIE", name: { fr: "Trésorerie", en: "Treasury", es: "Tesorería", de: "Treasury", it: "Tesoreria", nl: "Treasury", ar: "الخزينة" },
      positioning: RP_POSITIONING },
    { code: "FINTECH", name: { fr: "FinTech", en: "FinTech", es: "FinTech", de: "FinTech", it: "FinTech", nl: "FinTech", ar: "التكنولوجيا المالية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "RH", name: { fr: "Ressources Humaines", en: "Human Resources", es: "Recursos Humanos", de: "Personalwesen", it: "Risorse Umane", nl: "Human Resources", ar: "الموارد البشرية" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "RECRUTEMENT", name: { fr: "Recrutement / Talent Acquisition", en: "Recruitment / Talent Acquisition", es: "Selección / Talent Acquisition", de: "Recruiting / Talent Acquisition", it: "Recruiting / Talent Acquisition", nl: "Recruitment / Talent Acquisition", ar: "التوظيف واكتساب المواهب" },
      positioning: RP_POSITIONING },
    { code: "FORMATION", name: { fr: "Formation / Développement des talents", en: "Learning & Development", es: "Formación / Desarrollo del talento", de: "Weiterbildung / Talententwicklung", it: "Formazione / Sviluppo talenti", nl: "Opleiding / Talentontwikkeling", ar: "التدريب وتطوير المواهب" },
      positioning: RP_POSITIONING },
    { code: "PAIE", name: { fr: "Paie / ADP", en: "Payroll / HR Administration", es: "Nómina / Administración", de: "Lohnabrechnung / HR-Administration", it: "Paghe / Amministrazione", nl: "Salarisadministratie / HR-administratie", ar: "الرواتب وإدارة الموارد البشرية" },
      positioning: RP_POSITIONING },
    { code: "HRBP", name: { fr: "HR Business Partner", en: "HR Business Partner", es: "HR Business Partner", de: "HR Business Partner", it: "HR Business Partner", nl: "HR Business Partner", ar: "شريك أعمال الموارد البشرية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "DIRECTION_EXECUTIVE", name: { fr: "Direction & Haut Management", en: "Executive Leadership", es: "Dirección y Alta Dirección", de: "Geschäftsführung & Top Management", it: "Direzione e Top Management", nl: "Directie & Topmanagement", ar: "الإدارة العليا" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "DIRECTION_GENERALE", name: { fr: "Direction générale / CEO", en: "General Management / CEO", es: "Dirección general / CEO", de: "Geschäftsführung / CEO", it: "Direzione generale / CEO", nl: "Algemene directie / CEO", ar: "الإدارة العامة / الرئيس التنفيذي" },
      positioning: RP_POSITIONING },
    { code: "DIRECTION_FINANCIERE", name: { fr: "Direction financière / CFO", en: "Finance Leadership / CFO", es: "Dirección financiera / CFO", de: "Finanzleitung / CFO", it: "Direzione finanziaria / CFO", nl: "Financiële directie / CFO", ar: "المدير المالي / CFO" },
      positioning: RP_POSITIONING },
    { code: "DIRECTION_RH", name: { fr: "Direction RH / CHRO", en: "HR Leadership / CHRO", es: "Dirección RR. HH. / CHRO", de: "HR-Leitung / CHRO", it: "Direzione HR / CHRO", nl: "HR-directie / CHRO", ar: "مدير الموارد البشرية / CHRO" },
      positioning: RP_POSITIONING },
    { code: "DIRECTION_COMMERCIALE_EXEC", name: { fr: "Direction commerciale / CRO", en: "Sales Leadership / CRO", es: "Dirección comercial / CRO", de: "Vertriebsleitung / CRO", it: "Direzione commerciale / CRO", nl: "Commerciële directie / CRO", ar: "المدير التجاري / CRO" },
      positioning: RP_POSITIONING },
    { code: "DIRECTION_OPERATIONS", name: { fr: "Direction des opérations / COO", en: "Operations Leadership / COO", es: "Dirección de operaciones / COO", de: "Operationsleitung / COO", it: "Direzione operations / COO", nl: "Operationele directie / COO", ar: "مدير العمليات / COO" },
      positioning: RP_POSITIONING },
    { code: "DIRECTION_TECH", name: { fr: "Direction IT / CTO / CIO", en: "Technology Leadership / CTO / CIO", es: "Dirección tecnológica / CTO / CIO", de: "Technologieleitung / CTO / CIO", it: "Direzione tecnologia / CTO / CIO", nl: "Technologiedirectie / CTO / CIO", ar: "المدير التقني / CTO / CIO" },
      positioning: RP_POSITIONING },
    { code: "TRANSFORMATION", name: { fr: "Transformation / Stratégie", en: "Transformation / Strategy", es: "Transformación / Estrategia", de: "Transformation / Strategie", it: "Trasformazione / Strategia", nl: "Transformatie / Strategie", ar: "التحول والاستراتيجية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "INGENIERIE", name: { fr: "Ingénierie & Sciences", en: "Engineering & Science", es: "Ingeniería y Ciencias", de: "Ingenieurwesen & Wissenschaft", it: "Ingegneria e Scienze", nl: "Engineering & Wetenschappen", ar: "الهندسة والعلوم" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "INGENIERIE_MECANIQUE", name: { fr: "Ingénierie mécanique", en: "Mechanical Engineering", es: "Ingeniería mecánica", de: "Maschinenbau", it: "Ingegneria meccanica", nl: "Werktuigbouwkunde", ar: "الهندسة الميكانيكية" },
      positioning: RP_POSITIONING },
    { code: "INGENIERIE_ELECTRIQUE", name: { fr: "Ingénierie électrique", en: "Electrical Engineering", es: "Ingeniería eléctrica", de: "Elektrotechnik", it: "Ingegneria elettrica", nl: "Elektrotechniek", ar: "الهندسة الكهربائية" },
      positioning: RP_POSITIONING },
    { code: "INGENIERIE_ELECTRONIQUE", name: { fr: "Électronique / Systèmes embarqués", en: "Electronics / Embedded Systems", es: "Electrónica / Sistemas embebidos", de: "Elektronik / Embedded Systems", it: "Elettronica / Sistemi embedded", nl: "Elektronica / Embedded Systems", ar: "الإلكترونيات والأنظمة المدمجة" },
      positioning: RP_POSITIONING },
    { code: "INGENIERIE_PROCESS", name: { fr: "Process / Industrial Engineering", en: "Process / Industrial Engineering", es: "Procesos / Ingeniería industrial", de: "Prozess- / Wirtschaftsingenieurwesen", it: "Processi / Ingegneria industriale", nl: "Proces- / Industriële engineering", ar: "هندسة العمليات" },
      positioning: RP_POSITIONING },
    { code: "ROBOTIQUE", name: { fr: "Robotique / Automatisation", en: "Robotics / Automation", es: "Robótica / Automatización", de: "Robotik / Automatisierung", it: "Robotica / Automazione", nl: "Robotica / Automatisering", ar: "الروبوتات والأتمتة" },
      positioning: RP_POSITIONING },
  ]},
  { code: "SANTE", name: { fr: "Santé & Médico-social", en: "Healthcare & Care", es: "Salud y Atención", de: "Gesundheit & Pflege", it: "Sanità e Cura", nl: "Gezondheidszorg & Zorg", ar: "الصحة والرعاية" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "MEDECINS", name: { fr: "Médecins", en: "Medical Doctors", es: "Médicos", de: "Ärzte", it: "Medici", nl: "Artsen", ar: "الأطباء" },
      positioning: RP_POSITIONING },
    { code: "INFIRMIERS", name: { fr: "Infirmiers / Soins", en: "Nursing / Care", es: "Enfermería / Cuidados", de: "Pflege / Betreuung", it: "Infermieristica / Assistenza", nl: "Verpleegkunde / Zorg", ar: "التمريض والرعاية" },
      positioning: RP_POSITIONING },
    { code: "PHARMACIE", name: { fr: "Pharmacie", en: "Pharmacy", es: "Farmacia", de: "Pharmazie", it: "Farmacia", nl: "Farmacie", ar: "الصيدلة" },
      positioning: RP_POSITIONING },
    { code: "PARAMEDICAL", name: { fr: "Paramédical", en: "Allied Health", es: "Paramédico", de: "Gesundheitsfachberufe", it: "Professioni sanitarie", nl: "Paramedische beroepen", ar: "المهن الصحية المساندة" },
      positioning: RP_POSITIONING },
    { code: "SANTE_DIRECTION", name: { fr: "Direction / Management santé", en: "Healthcare Management", es: "Gestión sanitaria", de: "Gesundheitsmanagement", it: "Management sanitario", nl: "Directie / Management gezondheidszorg", ar: "إدارة الرعاية الصحية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "ENERGIE_ENVIRONNEMENT", name: { fr: "Énergie & Environnement", en: "Energy & Environment", es: "Energía y Medio Ambiente", de: "Energie & Umwelt", it: "Energia e Ambiente", nl: "Energie & Milieu", ar: "الطاقة والبيئة" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "ENERGIES_RENOUVELABLES", name: { fr: "Énergies renouvelables", en: "Renewable Energy", es: "Energías renovables", de: "Erneuerbare Energien", it: "Energie rinnovabili", nl: "Hernieuwbare energie", ar: "الطاقة المتجددة" },
      positioning: RP_POSITIONING },
    { code: "TRANSITION_ENERGETIQUE", name: { fr: "Transition énergétique", en: "Energy Transition", es: "Transición energética", de: "Energiewende", it: "Transizione energetica", nl: "Energietransitie", ar: "التحول في الطاقة" },
      positioning: RP_POSITIONING },
    { code: "ENVIRONNEMENT", name: { fr: "Environnement / ESG", en: "Environment / ESG", es: "Medio ambiente / ESG", de: "Umwelt / ESG", it: "Ambiente / ESG", nl: "Milieu / ESG", ar: "البيئة و ESG" },
      positioning: RP_POSITIONING },
    { code: "VEHICULES_ELECTRIQUES", name: { fr: "Mobilité électrique / véhicules autonomes", en: "Electric / Autonomous Vehicles", es: "Movilidad eléctrica / vehículos autónomos", de: "Elektro- / autonome Fahrzeuge", it: "Mobilità elettrica / veicoli autonomi", nl: "Elektrische mobiliteit / autonome voertuigen", ar: "المركبات الكهربائية والمستقلة" },
      positioning: RP_POSITIONING },
  ]},
  { code: "BANQUE_ASSURANCE", name: { fr: "Banque & Assurance", en: "Banking & Insurance", es: "Banca y Seguros", de: "Banken & Versicherungen", it: "Banche e Assicurazioni", nl: "Bankwezen & Verzekeringen", ar: "البنوك والتأمين" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "BANQUE", name: { fr: "Banque", en: "Banking", es: "Banca", de: "Bankwesen", it: "Banche", nl: "Bankwezen", ar: "الخدمات المصرفية" },
      positioning: RP_POSITIONING },
    { code: "ASSURANCE", name: { fr: "Assurance", en: "Insurance", es: "Seguros", de: "Versicherung", it: "Assicurazioni", nl: "Verzekeringen", ar: "التأمين" },
      positioning: RP_POSITIONING },
    { code: "RISQUE_CONFORMITE", name: { fr: "Risques / Compliance / KYC", en: "Risk / Compliance / KYC", es: "Riesgo / Compliance / KYC", de: "Risiko / Compliance / KYC", it: "Rischio / Compliance / KYC", nl: "Risico / Compliance / KYC", ar: "المخاطر والامتثال" },
      positioning: RP_POSITIONING },
  ]},
  { code: "MARKETING_COMMUNICATION", name: { fr: "Marketing & Communication", en: "Marketing & Communications", es: "Marketing y Comunicación", de: "Marketing & Kommunikation", it: "Marketing e Comunicazione", nl: "Marketing & Communicatie", ar: "التسويق والاتصال" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "MARKETING_DIGITAL", name: { fr: "Marketing digital", en: "Digital Marketing", es: "Marketing digital", de: "Digitales Marketing", it: "Marketing digitale", nl: "Digitale marketing", ar: "التسويق الرقمي" },
      positioning: RP_POSITIONING },
    { code: "CRM", name: { fr: "CRM / Customer Marketing", en: "CRM / Customer Marketing", es: "CRM / Marketing cliente", de: "CRM / Kundenmarketing", it: "CRM / Customer Marketing", nl: "CRM / Customer Marketing", ar: "إدارة علاقات العملاء" },
      positioning: RP_POSITIONING },
    { code: "COMMUNICATION", name: { fr: "Communication / Relations publiques", en: "Communications / PR", es: "Comunicación / RR. PP.", de: "Kommunikation / PR", it: "Comunicazione / PR", nl: "Communicatie / PR", ar: "الاتصال والعلاقات العامة" },
      positioning: RP_POSITIONING },
    { code: "PRODUIT_MARQUE", name: { fr: "Produit / Brand", en: "Product / Brand", es: "Producto / Marca", de: "Produkt / Marke", it: "Prodotto / Brand", nl: "Product / Brand", ar: "المنتج والعلامة التجارية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "JURIDIQUE", name: { fr: "Juridique & Compliance", en: "Legal & Compliance", es: "Legal y Compliance", de: "Recht & Compliance", it: "Legale e Compliance", nl: "Juridisch & Compliance", ar: "القانون والامتثال" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "DROIT_AFFAIRES", name: { fr: "Droit des affaires", en: "Business Law", es: "Derecho empresarial", de: "Wirtschaftsrecht", it: "Diritto d'impresa", nl: "Ondernemingsrecht", ar: "قانون الأعمال" },
      positioning: RP_POSITIONING },
    { code: "CONTRACTS", name: { fr: "Contrats", en: "Contracts", es: "Contratos", de: "Verträge", it: "Contratti", nl: "Contracten", ar: "العقود" },
      positioning: RP_POSITIONING },
    { code: "CONFORMITE", name: { fr: "Compliance / RGPD", en: "Compliance / GDPR", es: "Compliance / RGPD", de: "Compliance / DSGVO", it: "Compliance / GDPR", nl: "Compliance / AVG", ar: "الامتثال وحماية البيانات" },
      positioning: RP_POSITIONING },
  ]},
  { code: "TRANSPORT_MOBILITE", name: { fr: "Transport & Mobilité", en: "Transport & Mobility", es: "Transporte y Movilidad", de: "Transport & Mobilität", it: "Trasporti e Mobilità", nl: "Transport & Mobiliteit", ar: "النقل والتنقل" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "TRANSPORT_ROUTIER", name: { fr: "Transport routier", en: "Road Transport", es: "Transporte por carretera", de: "Straßentransport", it: "Trasporto stradale", nl: "Wegtransport", ar: "النقل البري" },
      positioning: RP_POSITIONING },
    { code: "AERIEN", name: { fr: "Aérien", en: "Aviation", es: "Aviación", de: "Luftfahrt", it: "Aviazione", nl: "Luchtvaart", ar: "الطيران" },
      positioning: RP_POSITIONING },
    { code: "MARITIME", name: { fr: "Maritime", en: "Maritime", es: "Marítimo", de: "Maritim", it: "Marittimo", nl: "Maritiem", ar: "النقل البحري" },
      positioning: RP_POSITIONING },
    { code: "FERROVIAIRE", name: { fr: "Ferroviaire", en: "Rail", es: "Ferroviario", de: "Bahn", it: "Ferroviario", nl: "Spoorwegen", ar: "السكك الحديدية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "AGROALIMENTAIRE", name: { fr: "Agroalimentaire & Agriculture", en: "Food & Agriculture", es: "Agroalimentación y Agricultura", de: "Lebensmittel & Landwirtschaft", it: "Agroalimentare e Agricoltura", nl: "Voedingsmiddelen & Landbouw", ar: "الأغذية والزراعة" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "AGRICULTURE", name: { fr: "Agriculture", en: "Agriculture", es: "Agricultura", de: "Landwirtschaft", it: "Agricoltura", nl: "Landbouw", ar: "الزراعة" },
      positioning: RP_POSITIONING },
    { code: "AGRO_PRODUCTION", name: { fr: "Production agroalimentaire", en: "Food Production", es: "Producción alimentaria", de: "Lebensmittelproduktion", it: "Produzione alimentare", nl: "Voedselproductie", ar: "إنتاج الأغذية" },
      positioning: RP_POSITIONING },
    { code: "QUALITE_ALIMENTAIRE", name: { fr: "Qualité / Sécurité alimentaire", en: "Food Quality / Safety", es: "Calidad / Seguridad alimentaria", de: "Lebensmittelqualität / Sicherheit", it: "Qualità / Sicurezza alimentare", nl: "Voedselkwaliteit / Voedselveiligheid", ar: "جودة وسلامة الغذاء" },
      positioning: RP_POSITIONING },
  ]},
  { code: "IMMOBILIER", name: { fr: "Immobilier & Construction patrimoniale", en: "Real Estate", es: "Inmobiliario", de: "Immobilien", it: "Immobiliare", nl: "Vastgoed & Vastgoedontwikkeling", ar: "العقارات" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "TRANSACTION", name: { fr: "Transaction", en: "Real Estate Sales", es: "Transacción", de: "Transaktion", it: "Intermediazione", nl: "Vastgoedtransacties", ar: "المعاملات العقارية" },
      positioning: RP_POSITIONING },
    { code: "GESTION_IMMOBILIERE", name: { fr: "Gestion immobilière", en: "Property Management", es: "Gestión inmobiliaria", de: "Immobilienverwaltung", it: "Gestione immobiliare", nl: "Vastgoedbeheer", ar: "إدارة العقارات" },
      positioning: RP_POSITIONING },
    { code: "ASSET_MANAGEMENT", name: { fr: "Asset / Property Management", en: "Asset / Property Management", es: "Asset / Property Management", de: "Asset / Property Management", it: "Asset / Property Management", nl: "Asset / Property Management", ar: "إدارة الأصول العقارية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "EDUCATION", name: { fr: "Éducation & Formation", en: "Education & Training", es: "Educación y Formación", de: "Bildung & Weiterbildung", it: "Istruzione e Formazione", nl: "Onderwijs & Opleiding", ar: "التعليم والتدريب" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "ENSEIGNEMENT", name: { fr: "Enseignement", en: "Teaching", es: "Enseñanza", de: "Lehre", it: "Insegnamento", nl: "Onderwijs", ar: "التدريس" },
      positioning: RP_POSITIONING },
    { code: "PEDAGOGIE", name: { fr: "Pédagogie / Ingénierie pédagogique", en: "Learning Design", es: "Diseño pedagógico", de: "Lernkonzeption", it: "Progettazione didattica", nl: "Pedagogiek / Onderwijskunde", ar: "التصميم التعليمي" },
      positioning: RP_POSITIONING },
    { code: "FORMATION_PRO", name: { fr: "Formation professionnelle", en: "Professional Training", es: "Formación profesional", de: "Berufliche Weiterbildung", it: "Formazione professionale", nl: "Beroepsopleiding", ar: "التدريب المهني" },
      positioning: RP_POSITIONING },
  ]},
  { code: "PHARMA_BIOTECH", name: { fr: "Pharma, Biotech & Life Sciences", en: "Pharma, Biotech & Life Sciences", es: "Farma, Biotech y Ciencias de la Vida", de: "Pharma, Biotech & Life Sciences", it: "Pharma, Biotech e Life Sciences", nl: "Farmacie, Biotech & Life Sciences", ar: "الأدوية والتكنولوجيا الحيوية" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "PHARMA", name: { fr: "Pharmaceutique", en: "Pharmaceutical", es: "Farmacéutico", de: "Pharma", it: "Farmaceutico", nl: "Farmaceutische sector", ar: "الصناعات الدوائية" },
      positioning: RP_POSITIONING },
    { code: "BIOTECH", name: { fr: "Biotechnologies", en: "Biotechnology", es: "Biotecnología", de: "Biotechnologie", it: "Biotecnologie", nl: "Biotechnologie", ar: "التكنولوجيا الحيوية" },
      positioning: RP_POSITIONING },
    { code: "CLINICAL_RESEARCH", name: { fr: "Recherche clinique", en: "Clinical Research", es: "Investigación clínica", de: "Klinische Forschung", it: "Ricerca clinica", nl: "Klinisch onderzoek", ar: "البحوث السريرية" },
      positioning: RP_POSITIONING },
  ]},
  { code: "LUXE_MODE", name: { fr: "Luxe, Mode & Beauté", en: "Luxury, Fashion & Beauty", es: "Lujo, Moda y Belleza", de: "Luxus, Mode & Beauty", it: "Lusso, Moda e Beauty", nl: "Luxe, Mode & Beauty", ar: "الفخامة والأزياء والجمال" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "LUXE", name: { fr: "Luxe", en: "Luxury", es: "Lujo", de: "Luxus", it: "Lusso", nl: "Luxe", ar: "الفخامة" },
      positioning: RP_POSITIONING },
    { code: "MODE", name: { fr: "Mode", en: "Fashion", es: "Moda", de: "Mode", it: "Moda", nl: "Mode", ar: "الأزياء" },
      positioning: RP_POSITIONING },
    { code: "BEAUTE", name: { fr: "Beauté / Cosmétique", en: "Beauty / Cosmetics", es: "Belleza / Cosmética", de: "Beauty / Kosmetik", it: "Beauty / Cosmetica", nl: "Beauty / Cosmetica", ar: "الجمال ومستحضرات التجميل" },
      positioning: RP_POSITIONING },
  ]},
  { code: "HOTELLERIE_TOURISME", name: { fr: "Hôtellerie, Restauration & Tourisme", en: "Hospitality, Food & Tourism", es: "Hostelería, Restauración y Turismo", de: "Hotellerie, Gastronomie & Tourismus", it: "Ospitalità, Ristorazione e Turismo", nl: "Horeca, Gastronomie & Toerisme", ar: "الضيافة والمطاعم والسياحة" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "HOTELLERIE", name: { fr: "Hôtellerie", en: "Hospitality", es: "Hostelería", de: "Hotellerie", it: "Ospitalità", nl: "Horeca", ar: "الضيافة" },
      positioning: RP_POSITIONING },
    { code: "RESTAURATION", name: { fr: "Restauration", en: "Food Service", es: "Restauración", de: "Gastronomie", it: "Ristorazione", nl: "Gastronomie / Food Service", ar: "المطاعم" },
      positioning: RP_POSITIONING },
    { code: "CASINO", name: { fr: "Casino & Jeux", en: "Casino & Gaming", es: "Casino y Juegos", de: "Casino & Glücksspiel", it: "Casinò e Giochi", nl: "Casino & Gaming", ar: "الكازينو والألعاب" },
      positioning: RP_POSITIONING },
    { code: "TOURISME", name: { fr: "Tourisme / Voyage", en: "Tourism / Travel", es: "Turismo / Viajes", de: "Tourismus / Reisen", it: "Turismo / Viaggi", nl: "Toerisme / Reizen", ar: "السياحة والسفر" },
      positioning: RP_POSITIONING },
  ]},
  { code: "PUBLIC_ASSOCIATIF", name: { fr: "Public, ONG & Associatif", en: "Public, NGO & Nonprofit", es: "Público, ONG y Asociativo", de: "Öffentlicher Sektor, NGO & Nonprofit", it: "Pubblico, ONG e Nonprofit", nl: "Publieke sector, NGO & Non-profit", ar: "القطاع العام والمنظمات غير الربحية" },
    positioning: RP_POSITIONING, subcategories: [
    { code: "ADMINISTRATION_PUBLIQUE", name: { fr: "Administration publique", en: "Public Administration", es: "Administración pública", de: "Öffentliche Verwaltung", it: "Pubblica amministrazione", nl: "Overheidsadministratie", ar: "الإدارة العامة" },
      positioning: RP_POSITIONING },
    { code: "ONG", name: { fr: "ONG / Humanitaire", en: "NGO / Humanitarian", es: "ONG / Humanitario", de: "NGO / Humanitär", it: "ONG / Umanitario", nl: "NGO / Humanitair", ar: "المنظمات غير الحكومية والعمل الإنساني" },
      positioning: RP_POSITIONING },
    { code: "ASSOCIATIF", name: { fr: "Associatif", en: "Nonprofit", es: "Asociativo", de: "Gemeinnützig", it: "Nonprofit", nl: "Non-profit / Verenigingen", ar: "العمل الجمعوي" },
      positioning: RP_POSITIONING },
  ]},
];

export const RP_TOP_SECTORS = RP_TAXONOMY.map(({ code, name }) => ({ code, name }));
