export type StrongProfile = {
  title: string;
  kind: "direction" | "management" | "expert" | "specialist" | "operations" | "project";
};

const COMMON: Record<string, StrongProfile[]> = {
  PRODUCTION: [
    { title: "Directeur / Responsable de production", kind: "direction" },
    { title: "Manager de production", kind: "management" },
    { title: "Responsable amélioration continue", kind: "management" },
    { title: "Expert process / industrialisation", kind: "expert" },
    { title: "Ingénieur méthodes senior", kind: "expert" },
    { title: "Chef de projet industriel", kind: "project" },
  ],
  MAINTENANCE: [
    { title: "Responsable maintenance", kind: "management" },
    { title: "Manager maintenance industrielle", kind: "management" },
    { title: "Expert maintenance / fiabilité", kind: "expert" },
    { title: "Ingénieur maintenance senior", kind: "expert" },
    { title: "Responsable méthodes maintenance", kind: "specialist" },
    { title: "Responsable GMAO / fiabilité", kind: "specialist" },
  ],
  QUALITE: [
    { title: "Responsable qualité / QHSE", kind: "management" },
    { title: "Manager qualité", kind: "management" },
    { title: "Expert qualité / amélioration continue", kind: "expert" },
    { title: "Responsable HSE", kind: "specialist" },
    { title: "Auditeur qualité senior", kind: "expert" },
    { title: "Référent conformité / normes", kind: "specialist" },
  ],
  METHODES_INDUSTRIELLES: [
    { title: "Responsable méthodes / industrialisation", kind: "management" },
    { title: "Manager industrialisation", kind: "management" },
    { title: "Expert industrialisation", kind: "expert" },
    { title: "Ingénieur process senior", kind: "expert" },
    { title: "Ingénieur méthodes senior", kind: "expert" },
    { title: "Chef de projet industrialisation", kind: "project" },
  ],
  SUPPLY_INDUSTRIELLE: [
    { title: "Responsable supply chain industrielle", kind: "management" },
    { title: "Supply Chain Manager", kind: "management" },
    { title: "Expert planification industrielle", kind: "expert" },
    { title: "Responsable flux / approvisionnements", kind: "specialist" },
    { title: "Demand Planner senior", kind: "expert" },
    { title: "Chef de projet supply chain", kind: "project" },
  ],
  LOGISTIQUE_TRANSPORT: [
    { title: "Responsable logistique / transport", kind: "management" },
    { title: "Directeur d'exploitation logistique", kind: "direction" },
    { title: "Responsable transport", kind: "management" },
    { title: "Expert optimisation des flux", kind: "expert" },
    { title: "Responsable affrètement", kind: "specialist" },
    { title: "Manager opérations logistiques", kind: "operations" },
  ],
  ACHATS: [
    { title: "Directeur achats", kind: "direction" },
    { title: "Responsable achats", kind: "management" },
    { title: "Category Manager senior", kind: "expert" },
    { title: "Acheteur stratégique", kind: "specialist" },
    { title: "Expert achats internationaux", kind: "expert" },
    { title: "Responsable procurement / sourcing", kind: "management" },
  ],
  SUPPLY_CHAIN: [
    { title: "Supply Chain Manager", kind: "management" },
    { title: "Responsable planification", kind: "management" },
    { title: "Responsable approvisionnements", kind: "management" },
    { title: "Demand Planner senior", kind: "expert" },
    { title: "S&OP Manager", kind: "expert" },
    { title: "Expert optimisation supply chain", kind: "expert" },
  ],
  PLANIFICATION: [
    { title: "Responsable planification / ordonnancement", kind: "management" },
    { title: "Planning Manager", kind: "management" },
    { title: "Expert ordonnancement", kind: "expert" },
    { title: "Planificateur industriel senior", kind: "expert" },
    { title: "Responsable capacité / charge", kind: "specialist" },
    { title: "Coordinateur flux senior", kind: "operations" },
  ],
  WAREHOUSING: [
    { title: "Responsable entrepôt", kind: "management" },
    { title: "Warehouse Manager", kind: "management" },
    { title: "Responsable exploitation logistique", kind: "management" },
    { title: "Expert WMS", kind: "expert" },
    { title: "Responsable flux magasin", kind: "specialist" },
    { title: "Chef de projet automatisation entrepôt", kind: "project" },
  ],
  VENTE_B2B: [
    { title: "Responsable commercial B2B", kind: "management" },
    { title: "Sales Manager", kind: "management" },
    { title: "Business Developer senior", kind: "expert" },
    { title: "Ingénieur commercial grands projets", kind: "specialist" },
    { title: "Account Executive senior", kind: "expert" },
    { title: "Expert vente complexe", kind: "expert" },
  ],
  GRANDS_COMPTES: [
    { title: "Key Account Manager senior", kind: "expert" },
    { title: "Responsable grands comptes", kind: "management" },
    { title: "Global Account Manager", kind: "management" },
    { title: "Strategic Account Manager", kind: "expert" },
    { title: "Expert vente complexe", kind: "expert" },
    { title: "Responsable partenariats stratégiques", kind: "specialist" },
  ],
  BUSINESS_DEV: [
    { title: "Responsable Business Development", kind: "management" },
    { title: "Business Developer senior", kind: "expert" },
    { title: "Head of Business Development", kind: "management" },
    { title: "Expert partenariats stratégiques", kind: "expert" },
    { title: "Responsable expansion / nouveaux marchés", kind: "specialist" },
    { title: "Chef de projet développement commercial", kind: "project" },
  ],
  DIRECTION_COMMERCIALE: [
    { title: "Directeur commercial", kind: "direction" },
    { title: "Head of Sales", kind: "management" },
    { title: "Sales Director régional / international", kind: "management" },
    { title: "Responsable grands comptes", kind: "management" },
    { title: "Sales Operations Manager", kind: "operations" },
    { title: "Expert stratégie commerciale", kind: "expert" },
  ],
  VENTE_RETAIL: [
    { title: "Directeur réseau / retail", kind: "direction" },
    { title: "Responsable régional", kind: "management" },
    { title: "Retail Manager", kind: "management" },
    { title: "Responsable réseau de points de vente", kind: "management" },
    { title: "Expert merchandising", kind: "expert" },
    { title: "Responsable expansion réseau", kind: "specialist" },
  ],
  DEV_LOGICIEL: [
    { title: "Engineering Manager", kind: "management" },
    { title: "Tech Lead senior", kind: "expert" },
    { title: "Software Architect", kind: "expert" },
    { title: "Staff / Principal Engineer", kind: "expert" },
    { title: "Expert backend / frontend", kind: "specialist" },
    { title: "Chef de projet technique", kind: "project" },
  ],
  DATA_IA: [
    { title: "Head of Data / Data Manager", kind: "management" },
    { title: "Data Scientist senior", kind: "expert" },
    { title: "Machine Learning Engineer", kind: "specialist" },
    { title: "Data Engineer senior", kind: "expert" },
    { title: "ML / AI Architect", kind: "expert" },
    { title: "Expert GenAI / LLM", kind: "specialist" },
  ],
  CYBERSECURITE: [
    { title: "RSSI / CISO", kind: "direction" },
    { title: "Security Manager", kind: "management" },
    { title: "Architecte cybersécurité", kind: "expert" },
    { title: "Expert SOC / réponse à incident", kind: "specialist" },
    { title: "Expert IAM / Zero Trust", kind: "specialist" },
    { title: "Pentester senior", kind: "expert" },
  ],
  CLOUD_DEVOPS: [
    { title: "Head of Cloud / Infrastructure", kind: "management" },
    { title: "Cloud Architect", kind: "expert" },
    { title: "DevOps / Platform Engineer senior", kind: "expert" },
    { title: "SRE senior", kind: "specialist" },
    { title: "Expert Kubernetes / Cloud", kind: "specialist" },
    { title: "FinOps / Cloud Cost Manager", kind: "expert" },
  ],
  ROBOTIQUE_IOT: [
    { title: "Responsable robotique / IoT", kind: "management" },
    { title: "Architecte systèmes embarqués", kind: "expert" },
    { title: "Ingénieur robotique senior", kind: "expert" },
    { title: "Expert automatisation", kind: "specialist" },
    { title: "Expert IoT / edge computing", kind: "specialist" },
    { title: "Chef de projet robotique", kind: "project" },
  ],
  PRODUIT_TECH: [
    { title: "Head of Product", kind: "management" },
    { title: "Product Manager senior", kind: "expert" },
    { title: "Product Owner senior", kind: "specialist" },
    { title: "UX Lead / UX Researcher senior", kind: "expert" },
    { title: "UI Design Lead", kind: "expert" },
    { title: "Product Operations Manager", kind: "operations" },
  ],
  COMPTABILITE: [
    { title: "Responsable comptable", kind: "management" },
    { title: "Accounting Manager", kind: "management" },
    { title: "Expert consolidation", kind: "expert" },
    { title: "Expert normes IFRS", kind: "specialist" },
    { title: "Responsable reporting financier", kind: "specialist" },
    { title: "Chef de projet transformation finance", kind: "project" },
  ],
  CONTROLE_DE_GESTION: [
    { title: "Responsable contrôle de gestion", kind: "management" },
    { title: "FP&A Manager", kind: "management" },
    { title: "Financial Controller senior", kind: "expert" },
    { title: "Expert business performance", kind: "expert" },
    { title: "Responsable reporting / BI finance", kind: "specialist" },
    { title: "Chef de projet finance transformation", kind: "project" },
  ],
  AUDIT: [
    { title: "Directeur audit", kind: "direction" },
    { title: "Manager audit", kind: "management" },
    { title: "Auditeur senior", kind: "expert" },
    { title: "Expert risques / contrôle interne", kind: "expert" },
    { title: "Expert IFRS / normes", kind: "specialist" },
    { title: "Responsable audit interne", kind: "management" },
  ],
  TRESORERIE: [
    { title: "Treasury Manager", kind: "management" },
    { title: "Responsable trésorerie", kind: "management" },
    { title: "Cash Manager senior", kind: "expert" },
    { title: "Expert financement", kind: "expert" },
    { title: "Expert cash management international", kind: "specialist" },
    { title: "Responsable risques financiers", kind: "specialist" },
  ],
  FINTECH: [
    { title: "FinTech Product Manager", kind: "management" },
    { title: "Expert paiements / moyens de paiement", kind: "specialist" },
    { title: "Expert risk / compliance FinTech", kind: "expert" },
    { title: "Architecte solutions financières", kind: "expert" },
    { title: "Product Manager senior", kind: "expert" },
    { title: "Chef de projet transformation financière", kind: "project" },
  ],
  RECRUTEMENT: [
    { title: "Talent Acquisition Manager", kind: "management" },
    { title: "Recruitment Lead", kind: "management" },
    { title: "Talent Partner senior", kind: "expert" },
    { title: "Executive Search Consultant", kind: "specialist" },
    { title: "Sourcing Expert / Headhunter", kind: "expert" },
    { title: "Responsable marque employeur", kind: "specialist" },
  ],
  FORMATION: [
    { title: "Responsable Learning & Development", kind: "management" },
    { title: "Talent Development Manager", kind: "management" },
    { title: "Learning Experience Designer senior", kind: "expert" },
    { title: "Expert ingénierie pédagogique", kind: "specialist" },
    { title: "Responsable academy / campus", kind: "management" },
    { title: "Chef de projet transformation des compétences", kind: "project" },
  ],
  PAIE: [
    { title: "Responsable paie", kind: "management" },
    { title: "Payroll Manager", kind: "management" },
    { title: "Expert paie internationale", kind: "expert" },
    { title: "Expert droit social / paie", kind: "specialist" },
    { title: "Responsable SIRH paie", kind: "specialist" },
    { title: "Chef de projet transformation paie", kind: "project" },
  ],
  HRBP: [
    { title: "HR Business Partner senior", kind: "expert" },
    { title: "HRBP Manager", kind: "management" },
    { title: "People Partner senior", kind: "expert" },
    { title: "Expert relations sociales", kind: "specialist" },
    { title: "Responsable transformation RH", kind: "management" },
    { title: "Talent / Workforce Planning Manager", kind: "management" },
  ],
  CONSEIL: [
    { title: "Partner / Directeur de conseil", kind: "direction" },
    { title: "Manager conseil", kind: "management" },
    { title: "Consultant senior", kind: "expert" },
    { title: "Expert sectoriel", kind: "specialist" },
    { title: "Principal / Expert transformation", kind: "expert" },
    { title: "Chef de projet transformation", kind: "project" },
  ],
  RELATION_CLIENT: [
    { title: "Customer Success Manager senior", kind: "management" },
    { title: "Head of Customer Success", kind: "management" },
    { title: "Customer Experience Manager", kind: "expert" },
    { title: "Expert fidélisation / rétention", kind: "specialist" },
    { title: "Responsable grands comptes clients", kind: "management" },
    { title: "Customer Operations Manager", kind: "operations" },
  ],
  OPERATIONS: [
    { title: "Operations Manager", kind: "management" },
    { title: "Head of Operations", kind: "management" },
    { title: "Responsable excellence opérationnelle", kind: "expert" },
    { title: "Process Excellence Lead", kind: "expert" },
    { title: "Expert optimisation des opérations", kind: "specialist" },
    { title: "Chef de projet transformation", kind: "project" },
  ],
  RESTAURATION: [
    { title: "Chef de cuisine", kind: "management" },
    { title: "Aide chef de cuisine", kind: "operations" },
    { title: "Sous-chef / Second de cuisine", kind: "management" },
    { title: "Responsable de cuisine", kind: "management" },
    { title: "Chef de partie", kind: "specialist" },
    { title: "Expert cuisine / gastronomie", kind: "expert" },
  ],
  CASINO: [
    { title: "Directeur de casino", kind: "direction" },
    { title: "Directeur des opérations casino", kind: "management" },
    { title: "Directeur / Responsable jeux", kind: "management" },
    { title: "Responsable tables de jeux", kind: "management" },
    { title: "Chef de salle / Pit Boss", kind: "management" },
    { title: "Croupier / Dealer", kind: "specialist" },
    { title: "Croupier jeux de table senior", kind: "expert" },
    { title: "Poker Dealer / Poker Room Manager", kind: "specialist" },
    { title: "Responsable machines à sous / Slot Manager", kind: "management" },
    { title: "Opérateur / Assistant machines à sous", kind: "operations" },
    { title: "Responsable caisse / Cashier Manager", kind: "management" },
    { title: "Caissier casino / Cashier", kind: "operations" },
    { title: "Responsable surveillance / Surveillance Manager", kind: "management" },
    { title: "Opérateur vidéosurveillance casino", kind: "specialist" },
    { title: "Responsable sécurité / Security Manager", kind: "management" },
    { title: "Agent de sécurité casino", kind: "operations" },
    { title: "Responsable conformité / AML-KYC", kind: "expert" },
    { title: "Compliance Officer / Responsable conformité jeux", kind: "specialist" },
    { title: "Responsable contrôle interne / risques", kind: "expert" },
    { title: "Responsable marketing casino", kind: "management" },
    { title: "CRM / Loyalty Manager casino", kind: "expert" },
    { title: "VIP Manager / Responsable clientèle VIP", kind: "management" },
    { title: "Responsable événements / Entertainment", kind: "management" },
    { title: "Responsable restauration casino", kind: "management" },
    { title: "Chef de cuisine casino", kind: "specialist" },
    { title: "Responsable hôtel / Hébergement", kind: "management" },
    { title: "Responsable maintenance technique", kind: "management" },
    { title: "Technicien machines de jeux / Gaming Technician", kind: "specialist" },
    { title: "IT Manager / Responsable systèmes casino", kind: "management" },
    { title: "Administrateur systèmes / réseaux casino", kind: "expert" },
    { title: "Responsable RH casino", kind: "management" },
    { title: "Responsable formation jeux / Gaming Trainer", kind: "specialist" },
    { title: "Responsable comptable / Finance casino", kind: "management" },
    { title: "Responsable achats / approvisionnements", kind: "management" },
    { title: "Responsable expérience client", kind: "expert" },
    { title: "Responsable développement / partenariats", kind: "management" },
  ],
  SERVICES_GENERAUX: [
    { title: "Responsable services généraux", kind: "management" },
    { title: "Facility Manager", kind: "management" },
    { title: "Responsable environnement de travail", kind: "specialist" },
    { title: "Expert sûreté / sécurité des sites", kind: "specialist" },
    { title: "Responsable multi-sites", kind: "management" },
    { title: "Chef de projet immobilier / facilities", kind: "project" },
  ],
};

const SECTOR_FALLBACKS: Record<string, string[]> = {
  BTP: ["Directeur de travaux", "Conducteur de travaux senior", "Responsable d'affaires", "Expert technique", "Chef de projet", "Ingénieur senior"],
  SANTE: ["Médecin spécialiste", "Cadre de santé", "Responsable de service", "Expert clinique", "Professionnel de santé senior", "Coordinateur de soins"],
  ENERGIE_ENVIRONNEMENT: ["Responsable énergie", "Energy Manager", "Expert transition énergétique", "Expert ESG / environnement", "Ingénieur senior", "Chef de projet transition"],
  BANQUE_ASSURANCE: ["Responsable métier", "Manager senior", "Expert risques", "Expert conformité", "Expert financier", "Chef de projet transformation"],
  MARKETING_COMMUNICATION: ["Head of Marketing", "Marketing Manager", "Brand Manager senior", "Expert acquisition / digital", "Expert CRM", "Chef de projet communication"],
  JURIDIQUE: ["Directeur juridique", "Responsable juridique", "Juriste senior", "Expert compliance", "Expert RGPD", "Contract Manager"],
  TRANSPORT_MOBILITE: ["Directeur opérations", "Responsable exploitation", "Expert mobilité", "Ingénieur transport senior", "Expert sécurité", "Chef de projet mobilité"],
  AGROALIMENTAIRE: ["Responsable production", "Responsable qualité", "Expert sécurité alimentaire", "Responsable R&D", "Expert process", "Chef de projet industriel"],
  IMMOBILIER: ["Directeur immobilier", "Asset Manager senior", "Property Manager senior", "Expert investissement", "Responsable développement", "Chef de projet immobilier"],
  EDUCATION: ["Directeur d'établissement", "Responsable pédagogique", "Expert ingénierie pédagogique", "Formateur senior", "Responsable formation", "Chef de projet éducation"],
  PHARMA_BIOTECH: ["Directeur médical", "Responsable affaires réglementaires", "Expert biotech", "Clinical Research Manager", "Expert qualité pharma", "Scientifique senior"],
  LUXE_MODE: ["Directeur de marque", "Retail Manager", "Responsable collection", "Expert produit", "Expert merchandising", "Chef de projet développement"],
  HOTELLERIE_TOURISME: ["Directeur d'établissement", "Hotel Manager", "Responsable opérations", "Revenue Manager", "Expert expérience client", "Chef de projet tourisme"],
  PUBLIC_ASSOCIATIF: ["Directeur d'établissement / service", "Responsable de programme", "Expert politiques publiques", "Chef de projet senior", "Responsable partenariats", "Expert financement / subventions"],
  INGENIERIE: ["Engineering Manager", "Lead Engineer", "Ingénieur senior", "Expert technique", "Architecte système", "Chef de projet R&D"],
  DIRECTION_EXECUTIVE: ["CEO / Directeur général", "CFO / Directeur financier", "CHRO / Directeur RH", "CRO / Directeur commercial", "COO / Directeur des opérations", "CTO / CIO"],
};

export function getStrongProfilesForProfession(sectorCode: string, professionCode: string): StrongProfile[] {
  return COMMON[professionCode] ?? (SECTOR_FALLBACKS[sectorCode] ?? [
    "Responsable métier",
    "Manager senior",
    "Expert senior",
    "Spécialiste rare",
    "Chef de projet senior",
    "Référent métier",
  ]).map((title, index) => ({
    title,
    kind: index < 2 ? "management" : index < 4 ? "expert" : "specialist",
  }));
}
