export type CompanyScoringInput = { type?: string | null; recruitmentVolume?: number | null; strategicRecruitment?: boolean; seniority?: string | null; budgetLevel?: "LOW" | "MEDIUM" | "HIGH" | null; hiringDifficulty?: "LOW" | "MEDIUM" | "HIGH" | null; growthSignals?: string[] | null; internationalScope?: string[] | null; sectorTension?: "LOW" | "MEDIUM" | "HIGH" | null; decisionMakerIdentified?: boolean; currentNeed?: boolean; recurringPotential?: "PUNCTUAL" | "RECURRING" | "STRATEGIC" | null; specialtyFit?: "LOW" | "MEDIUM" | "HIGH" | null };
export type CompanyScoreResult = { score: number; tier: "PROSPECT" | "PRIORITAIRE" | "COMPTE_STRATEGIQUE"; breakdown: Record<string, number>; reasons: string[] };
const level = (value?: string | null) => value === "HIGH" ? 1 : value === "MEDIUM" ? 0.6 : 0;
export function scoreCompany(input: CompanyScoringInput): CompanyScoreResult {
  const breakdown = { budget: Math.round(level(input.budgetLevel) * 15), recruitmentValue: Math.min(15, (input.recruitmentVolume ?? 0) * 3 + (input.strategicRecruitment ? 6 : 0)), seniority: /c-level|dirige|executive|cadre|expert/i.test(input.seniority ?? "") ? 12 : 5, difficulty: Math.round(level(input.hiringDifficulty) * 10), growth: Math.min(10, (input.growthSignals?.length ?? 0) * 3), international: Math.min(10, (input.internationalScope?.length ?? 0) * 2), sector: Math.round(level(input.sectorTension) * 8), decisionMaker: input.decisionMakerIdentified ? 5 : 0, currentNeed: input.currentNeed ? 5 : 0, recurring: input.recurringPotential === "STRATEGIC" ? 10 : input.recurringPotential === "RECURRING" ? 7 : 2, specialtyFit: Math.round(level(input.specialtyFit) * 5) };
  const score = Math.max(0, Math.min(100, Object.values(breakdown).reduce((sum, value) => sum + value, 0)));
  const tier = score >= 85 ? "COMPTE_STRATEGIQUE" : score >= 70 ? "PRIORITAIRE" : "PROSPECT";
  const reasons = [input.currentNeed ? "Besoin de recrutement actuellement identifié." : "Besoin actuel non confirmé.", input.decisionMakerIdentified ? "Interlocuteur décisionnaire identifié." : "Décisionnaire encore à identifier.", input.recurringPotential === "STRATEGIC" ? "Fort potentiel de relation long terme." : input.recurringPotential === "RECURRING" ? "Potentiel de recrutements récurrents." : "Potentiel actuellement ponctuel."];
  return { score, tier, breakdown, reasons };
}
