import { redirect } from "next/navigation";
import { requireConsultantAccess } from "@/lib/consultant-access";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { matchCandidateToJob } from "@/lib/matching";

export default async function ConsultantCandidaturesPage(){
 const access=await requireConsultantAccess().catch(()=>null); if(!access) redirect("/connexion");
 const applications=await prisma.application.findMany({select:{id:true,status:true,updatedAt:true,candidate:{select:{headline:true,bio:true,skills:true,experienceYears:true,user:{select:{name:true,email:true}}}},job:{select:{title:true,description:true,requiredSkills:true,requiredExperienceYears:true,company:{select:{name:true}}}}},orderBy:{updatedAt:"desc"},take:200});
 const rows=applications.map(a=>({...a,matching:matchCandidateToJob({headline:a.candidate.headline,bio:a.candidate.bio,skills:a.candidate.skills,experienceYears:a.candidate.experienceYears},{title:a.job.title,description:a.job.description,requiredSkills:a.job.requiredSkills,requiredExperienceYears:a.job.requiredExperienceYears})}));
 return <section className="mx-auto w-[min(1180px,calc(100%-40px))] py-12 md:w-[min(1180px,calc(100%-72px))]"><p className="text-[10px] uppercase tracking-[0.35em] text-[#c7a15a]">Espace consultant · Candidatures</p><h1 className="mt-4 font-serif text-4xl sm:text-5xl">Pipeline candidats.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50">Vue dédiée aux dossiers, au statut et au score de compatibilité. Les données restent dans le périmètre consultant.</p><Link href="/espace/consultant" className="mt-6 inline-block border border-white/15 px-4 py-2.5 text-[10px] uppercase tracking-[0.18em] text-white/60">← Retour</Link><div className="mt-10 space-y-3">{rows.map(a=><article key={a.id} className="border border-white/10 bg-[#111] p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-serif text-xl">{a.candidate.user.name||a.candidate.user.email}</p><p className="mt-1 text-xs text-white/40">{a.candidate.headline||"Profil professionnel"} · {a.job.title} · {a.job.company.name}</p><p className="mt-3 text-xs text-white/45">Compétences {a.matching.skillMatches}/{a.matching.requiredSkills||"—"} · Expérience {a.matching.experienceYears??"—"}/{a.matching.requiredExperienceYears??"—"} ans</p></div><div className="text-right"><p className="font-serif text-3xl text-[#c7a15a]">{a.matching.score}%</p><span className="text-[10px] uppercase tracking-[0.14em] text-white/40">{a.status}</span></div></div></article>)}{rows.length===0&&<div className="border border-white/10 p-6 text-sm text-white/45">Aucune candidature à afficher.</div>}</div></section>
}